### ISSUE TITLE
请教一个关于coding持续集成的问题

### ISSUE THREAD

**Issue by tiexo** [JackCh3n/hexo-template#1]
试了下你博客的持续集成方法，确实有效，感谢！
但是我最近几天看了一篇文章：https://blog.coding.net/blog/Hexo
尝试根据里面的教程来操作，卡在了最后一步 hexo d，提示没有ssh权限，同样查了很多资料，都没有解决这个问题。不知道博主为什么没有用hexo d命令？还有这个链接的方法是否可行？

**Comment by Kepontry** [comment]
可以尝试用一下Travis CI，差不多的作用

**Comment by JackCh3n** [comment]
> 试了下你博客的持续集成方法，确实有效，感谢！
> 但是我最近几天看了这篇文章：[https](https://blog.coding.net/blog/Hexo) : 
> //blog.coding.net/blog/Hexo尝试根据里面的教程来操作，卡在了最后一步hexo d，提示没有ssh权限，同样查了很多资料，都没有解决这个问题。不知道博主为什么没有用hexo d命令？还有这个链接的方法是否可行？
原理就是基于docker然后进行编译打包,我是用的自己做的docker包进行编译的,所以没有遇到出现hexo d没有权限的问题

**Comment by JackCh3n** [comment]
> 可以尝试用一下Travis CI，差不多的作用

原理都市差不多的,只是一个是coding内部完成全部的操作,一个是第三方插手,都是基于docker打包好的环境进行编译和发布的.coding内部产品可以实现我想要的功能,当然是优先支持内部.
